# .github/workflows/nodejs.yml
name: Run Jest Tests

# Ejecuta esta acción en los eventos de 'push' o 'pull_request' al repositorio
on:
  push:
    branches:
      - main    # Puedes cambiar la rama según tu preferencia
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Configura el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configura Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Usa la versión de Node.js que prefieras

    # Instala las dependencias
    - name: Install dependencies
      run: npm install

    # Ejecuta las pruebas
    - name: Run Jest tests
      run: npm test
